<?php 

class Constants{
    const HEALTH_STATUS_SUSPICIOUS =  '1';
    const HEALTH_STATUS_CONFIRMED = '2';
    //const HEALTH_STATUS_CONFIRMED = '3';
    const HEALTH_STATUS_RECOVERED = '4';
    const HEALTH_STATUS_DISCARDED =  '10';
    const HEALTH_STATUS_DESEASED = '11';
   /* const HEALTH_STATUS_CONFIRMED = '5';
    const HEALTH_STATUS_CONFIRMED = '6';
    const HEALTH_STATUS_CONFIRMED = '7';
    const HEALTH_STATUS_CONFIRMED = '8';
    const HEALTH_STATUS_CONFIRMED = '9';
    
  
    const HEALTH_STATUS_CONFIRMED = '12';
    const HEALTH_STATUS_CONFIRMED = '13';
    const HEALTH_STATUS_CONFIRMED = '14';
    const HEALTH_STATUS_CONFIRMED = '15';
    const HEALTH_STATUS_CONFIRMED = '16';
    const HEALTH_STATUS_CONFIRMED = '17';*/
 
    
}